services:
  - type: web
    name: ai-web-scraper
    env: docker
    plan: free
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: RENDER
        value: true
    packages:
      - google-chrome-stable
      - chromium-browser
      - chromium-driver
      - wget
      - curl
      - unzip
      - gnupg
      - apt-transport-https
      - ca-certificates 