services:
  - type: web
    name: ai-web-scraper
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: RENDER
        value: true
    packages:
      - google-chrome-stable
      - chromium-driver 