services:
  - type: web
    name: ai-web-scraper
    env: python
    buildCommand: bash build.sh
    startCommand: streamlit run main.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHONUNBUFFERED
        value: true
      - key: RENDER
        value: true
    packages:
      - google-chrome-stable
      - chromium-browser
      - chromium-driver
      - wget
      - curl
      - unzip
      - gnupg
      - apt-transport-https
      - ca-certificates 